controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.22
    wheel_radius: 0.06

    publish_rate: 50.0
    base_frame_id: base_link

    # cmd_vel interface
    use_stamped_vel: false

    # odom
    enable_odom_tf: true
    odom_frame_id: odom
